kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-newns-sept30-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: test-newns-sept30-dsp-job
    namespace: custom-namespace-app-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-newns-sept30-imagestream-job-role
