apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-newns-sept30
  janus-idp.io/tekton: test-newns-sept30
  backstage.io/kubernetes-id: test-newns-sept30
  backstage.io/kubernetes-namespace: custom-namespace-app-development 
  app.kubernetes.io/part-of: test-newns-sept30
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
